"""Resumable experiment runner for the OpenBinding4Placement (CLASP-FaaS) campaign.

Design (see the paper's experimental setup):

- Corpus: the priced 1-seed BIM' corpus (3 applications x 35 infrastructure
  sizes, dataset seed 146588263), generated by ``experimentation.icsoc.bimstar``.
- Stopping criterion: a single wall-clock budget T (TIME_BUDGET_MS, default
  300 s) shared by every algorithm. Heuristics additionally guarantee at
  least 1000 evaluations (the literature baseline budget), which is the
  fallback measurement when the exact solver is UNSAT / finds no solution.
  Since best-so-far traces record (eval_index, elapsed_ms), results for any
  cutoff tau <= T — including the 1000-evaluation cutoff — are derived
  offline from the traces.
- Engines / algorithms (all mono-objective, canonical weighted objective):
    * ``minizinc-csp``  — exact CP solver (Gecode), 1 run/instance,
      time limit T, anytime incumbent trace.
    * ``random-search`` — uniform random search, budget T (>= 1000 evals),
      10 repetitions (seeds 1..10), best-so-far trace.
    * ``evolutionary-heuristics`` — NSGA-II in MONO mode, population 20,
      budget T (>= 1000 evals), 10 repetitions (seeds 1..10), best-so-far trace.
- Every returned binding is re-evaluated with the gateway reference evaluator
  (single source of truth); a mismatch marks the run as suspect.
- Results are appended incrementally to CSV files; already-recorded run ids
  are skipped, so the campaign can be interrupted and resumed at any time.
"""

from __future__ import annotations

import csv
import json
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterator

import httpx

from openbinding_gateway.semantics import evaluate_solution

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_CORPUS = REPO_ROOT / "experimentation/icsoc/out/bimstar-priced/instances"
DEFAULT_RESULTS = REPO_ROOT / "experimentation/icsoc/out/results"
DEFAULT_GATEWAY = "http://localhost:8000"

# Wall-clock stopping criterion shared by every algorithm.
TIME_BUDGET_MS = 300_000
# Minimum evaluations always granted to the heuristics (fallback baseline
# for instances where the exact solver fails).
HEURISTIC_MIN_EVALUATIONS = 1_000
HEURISTIC_SEEDS = tuple(range(1, 11))
GA_POPULATION = 20

RUN_FIELDS = [
    "run_id", "application", "infra_size", "dataset_seed", "instance_id",
    "engine", "seed", "options", "status", "feasibility", "feasible",
    "objective_value", "engine_objective_value", "oracle_match",
    "cost", "latency", "security",
    "engine_execution_time_ms", "engine_evaluations", "wall_time_s", "solver_status",
    "n_tasks", "n_candidates", "error",
]
TRACE_FIELDS = [
    "run_id", "engine", "seed", "source", "eval_index", "elapsed_ms",
    "best_objective", "feasible", "hard_violation",
]
CORPUS_FIELDS = [
    "instance_id", "application", "infra_size", "dataset_seed",
    "n_tasks", "n_candidates", "n_pools", "n_features",
    "n_constraints_local", "n_constraints_global", "n_constraints_dependency",
    "n_resource_capacity", "n_transitions", "n_budget_constraints",
    "log10_binding_space", "global_budget",
]


@dataclass
class RunSpec:
    engine: str
    seed: int | None
    options: dict[str, Any]

    @property
    def label(self) -> str:
        return self.engine if self.seed is None else f"{self.engine}#seed{self.seed}"


def campaign_specs(time_budget_ms: int = TIME_BUDGET_MS) -> list[RunSpec]:
    specs: list[RunSpec] = [
        RunSpec("minizinc-csp", None, {
            "time_limit_ms": time_budget_ms, "intermediate_solutions": True,
        }),
    ]
    for seed in HEURISTIC_SEEDS:
        specs.append(RunSpec("random-search", seed, {
            "iterations_count": HEURISTIC_MIN_EVALUATIONS,
            "time_budget_ms": time_budget_ms,
            "seed": seed,
        }))
    for seed in HEURISTIC_SEEDS:
        specs.append(RunSpec("evolutionary-heuristics", seed, {
            # UNIFORM = uniform crossover + random-reset mutation (categorical
            # candidate indices). Selected in the preliminary 3-way pilot
            # (pilot_ga.py): feasibility 9/9 vs 7/9 (SBX) on arOrch, same
            # median J, and far better J at the classic 1000-eval cutoff.
            "algorithm": "NSGAII", "operators": "UNIFORM",
            "population_size": GA_POPULATION,
            "max_evaluations": HEURISTIC_MIN_EVALUATIONS,
            "time_budget_ms": time_budget_ms,
            "seed": seed,
        }))
    return specs


def iter_instances(corpus: Path = DEFAULT_CORPUS) -> Iterator[Path]:
    yield from sorted(corpus.glob("*/*/infrastructure_*.bimstar.json"))


def instance_meta(instance: dict[str, Any], path: Path) -> dict[str, Any]:
    md = instance.get("metadata", {})
    size = path.stem.replace("infrastructure_", "").replace(".bimstar", "")
    return {
        "instance_id": md.get("id", path.stem),
        "application": md.get("application_id", path.parts[-3]),
        "dataset_seed": md.get("dataset_seed", path.parts[-2]),
        "infra_size": int(size),
    }


def corpus_summary_row(instance: dict[str, Any], path: Path) -> dict[str, Any]:
    import math

    meta = instance_meta(instance, path)
    per_task: dict[str, int] = {}
    for cand in instance["candidates"]:
        per_task[cand["task_id"]] = per_task.get(cand["task_id"], 0) + 1
    log10_space = sum(math.log10(max(1, n)) for n in per_task.values())

    counts = {"LOCAL": 0, "GLOBAL": 0, "DEPENDENCY": 0, "BUDGET": 0}
    global_budget = None
    for c in instance.get("constraints", []):
        if c.get("kind") == "DEPENDENCY":
            counts["DEPENDENCY"] += 1
        elif c.get("scope") == "GLOBAL":
            counts["GLOBAL"] += 1
        else:
            counts["LOCAL"] += 1
        if str(c.get("id", "")).startswith("budget"):
            counts["BUDGET"] += 1
            if c.get("scope") == "GLOBAL":
                global_budget = c.get("value")

    return {
        **meta,
        "n_tasks": len(instance["tasks"]),
        "n_candidates": len(instance["candidates"]),
        "n_pools": len(instance.get("resource_model", {}).get("pools", [])),
        "n_features": len(instance.get("features", [])),
        "n_constraints_local": counts["LOCAL"],
        "n_constraints_global": counts["GLOBAL"],
        "n_constraints_dependency": counts["DEPENDENCY"],
        "n_resource_capacity": len(instance.get("resource_model", {}).get("constraints", [])),
        "n_transitions": len(instance.get("latency_model", {}).get("transition_constraints", [])),
        "n_budget_constraints": counts["BUDGET"],
        "log10_binding_space": round(log10_space, 3),
        "global_budget": global_budget,
    }


def solve_via_gateway(
    base_url: str,
    engine_id: str,
    instance: dict[str, Any],
    options: dict[str, Any],
    poll_interval: float = 2.0,
    max_poll_s: float = 1800.0,
) -> tuple[dict[str, Any], float]:
    started = time.time()
    with httpx.Client(timeout=max(960.0, max_poll_s)) as client:
        response = client.post(
            f"{base_url}/v1/solve",
            json={"engine_id": engine_id, "instance": instance, "options": options},
        )
        if response.status_code not in (200, 202):
            return {"error": f"HTTP {response.status_code}: {response.text[:300]}"}, time.time() - started
        data = response.json()
        job_id = data.get("job_id")
        while data.get("status") in ("queued", "running"):
            if time.time() - started > max_poll_s:
                return {"error": f"polling timed out after {max_poll_s}s"}, time.time() - started
            time.sleep(poll_interval)
            data = client.get(f"{base_url}/v1/jobs/{job_id}").json()
    return data, time.time() - started


def _append_csv(path: Path, fields: list[str], rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    new_file = not path.exists()
    with path.open("a", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fields, extrasaction="ignore")
        if new_file:
            writer.writeheader()
        writer.writerows(rows)


def _completed_run_ids(runs_csv: Path) -> set[str]:
    if not runs_csv.exists():
        return set()
    with runs_csv.open(encoding="utf-8") as fh:
        return {row["run_id"] for row in csv.DictReader(fh) if row.get("status") == "ok"}


def _run_row_and_traces(
    run_id: str,
    meta: dict[str, Any],
    spec: RunSpec,
    instance: dict[str, Any],
    data: dict[str, Any],
    wall_s: float,
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    row: dict[str, Any] = {
        "run_id": run_id,
        **meta,
        "engine": spec.engine,
        "seed": spec.seed,
        "options": json.dumps(spec.options, sort_keys=True),
        "wall_time_s": round(wall_s, 3),
        "n_tasks": len(instance["tasks"]),
        "n_candidates": len(instance["candidates"]),
    }
    traces: list[dict[str, Any]] = []

    if data.get("error") and not data.get("result"):
        row.update({"status": "error", "error": str(data.get("error"))[:300]})
        return row, traces

    result = data.get("result") or {}
    provenance = result.get("provenance") or {}
    metadata = provenance.get("metadata") or {}
    row["feasibility"] = result.get("feasibility")
    row["engine_execution_time_ms"] = provenance.get("execution_time_ms")
    # Total evaluations performed by the heuristics (exact budget utilization;
    # traces only bound it by the index of the last improvement). The GA
    # reports it as 'evaluations', random search as 'iterations_count'.
    row["engine_evaluations"] = metadata.get("evaluations", metadata.get("iterations_count"))
    row["solver_status"] = metadata.get("status")

    solutions = result.get("solutions") or []
    if not solutions:
        row["status"] = "ok"
        row["feasible"] = False
        row["error"] = str(data.get("error") or metadata.get("error") or "")[:300]
    else:
        solution = solutions[0]
        oracle = evaluate_solution(instance, solution.get("binding") or {})
        engine_reported = solution.get("engine_objective_value")
        # Integrity audit: the engine's internal search objective must equal
        # the canonical objective for feasible solutions (infeasible GA bests
        # intentionally carry Deb's offset, so the audit only applies when
        # the reference evaluator confirms feasibility).
        oracle_match = None
        if oracle["feasible"] and engine_reported is not None:
            oracle_match = abs(float(engine_reported) - oracle["objective_value"]) < 1e-6
        row.update({
            "status": "ok",
            "feasible": oracle["feasible"],
            "objective_value": oracle["objective_value"],
            "engine_objective_value": engine_reported,
            "oracle_match": oracle_match,
            "cost": oracle["aggregated_features"].get("cost"),
            "latency": oracle["aggregated_features"].get("latency"),
            "security": oracle["aggregated_features"].get("security"),
        })

    for entry in metadata.get("trace") or []:
        if isinstance(entry, dict) and "eval_index" in entry:
            traces.append({
                "run_id": run_id, "engine": spec.engine, "seed": spec.seed,
                "source": "search",
                "eval_index": entry.get("eval_index"),
                "elapsed_ms": entry.get("elapsed_ms"),
                "best_objective": entry.get("best_objective"),
                "feasible": entry.get("feasible"),
                "hard_violation": entry.get("hard_violation"),
            })
        elif isinstance(entry, dict):  # MiniZinc incumbents
            traces.append({
                "run_id": run_id, "engine": spec.engine, "seed": spec.seed,
                "source": "incumbent",
                "eval_index": None,
                "elapsed_ms": entry.get("elapsed_ms"),
                "best_objective": entry.get("objective_value"),
                "feasible": True,
                "hard_violation": 0.0,
            })
    return row, traces


def print_status(
    corpus: Path = DEFAULT_CORPUS,
    results_dir: Path = DEFAULT_RESULTS,
) -> None:
    """Progress report: completed runs per engine, error counts, rough ETA."""
    runs_csv = results_dir / "runs.csv"
    n_instances = len(list(iter_instances(corpus)))
    expected = {
        "minizinc-csp": n_instances,
        "random-search": n_instances * len(HEURISTIC_SEEDS),
        "evolutionary-heuristics": n_instances * len(HEURISTIC_SEEDS),
    }
    if not runs_csv.exists():
        print(f"No runs recorded yet ({runs_csv} missing). "
              f"Expected total: {sum(expected.values())} runs over {n_instances} instances.")
        return

    with runs_csv.open(encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))

    print(f"{len(rows)}/{sum(expected.values())} runs recorded in {runs_csv}")
    for engine, total in expected.items():
        engine_rows = [r for r in rows if r.get("engine") == engine]
        ok = [r for r in engine_rows if r.get("status") == "ok"]
        errors = len(engine_rows) - len(ok)
        walls = [float(r["wall_time_s"]) for r in ok if r.get("wall_time_s")]
        mean_wall = sum(walls) / len(walls) if walls else 0.0
        remaining = total - len(ok)
        eta_h = remaining * mean_wall / 3600 if walls else float("nan")
        feasible = sum(1 for r in ok if r.get("feasible") == "True")
        print(
            f"  {engine:26s} {len(ok):5d}/{total:<5d} ok "
            f"({feasible} feasible, {errors} errors) "
            f"mean {mean_wall:6.1f}s/run  ETA lane ~{eta_h:5.1f} h"
        )


def write_corpus_summary(
    corpus: Path = DEFAULT_CORPUS,
    results_dir: Path = DEFAULT_RESULTS,
) -> Path:
    rows = []
    for path in iter_instances(corpus):
        with path.open(encoding="utf-8") as fh:
            instance = json.load(fh)
        rows.append(corpus_summary_row(instance, path))
    out = results_dir / "corpus_summary.csv"
    if out.exists():
        out.unlink()
    _append_csv(out, CORPUS_FIELDS, rows)
    return out


def run_campaign(
    corpus: Path = DEFAULT_CORPUS,
    results_dir: Path = DEFAULT_RESULTS,
    base_url: str = DEFAULT_GATEWAY,
    applications: set[str] | None = None,
    sizes: set[int] | None = None,
    engines: set[str] | None = None,
    time_budget_ms: int = TIME_BUDGET_MS,
    verbose: bool = True,
) -> None:
    """Run (or resume) the campaign; skips run ids already recorded as ok."""
    runs_csv = results_dir / "runs.csv"
    traces_csv = results_dir / "traces.csv"
    done = _completed_run_ids(runs_csv)
    specs = campaign_specs(time_budget_ms)

    for path in iter_instances(corpus):
        with path.open(encoding="utf-8") as fh:
            instance = json.load(fh)
        meta = instance_meta(instance, path)
        if applications and meta["application"] not in applications:
            continue
        if sizes and meta["infra_size"] not in sizes:
            continue

        for spec in specs:
            if engines and spec.engine not in engines:
                continue
            run_id = f"{meta['instance_id']}|{spec.label}"
            if run_id in done:
                continue
            data, wall_s = solve_via_gateway(
                base_url, spec.engine, instance, spec.options,
                max_poll_s=time_budget_ms / 1000 + 900,
            )
            row, traces = _run_row_and_traces(run_id, meta, spec, instance, data, wall_s)
            _append_csv(runs_csv, RUN_FIELDS, [row])
            if traces:
                _append_csv(traces_csv, TRACE_FIELDS, traces)
            done.add(run_id)
            if verbose:
                print(
                    f"{run_id}: status={row.get('status')} feasible={row.get('feasible')} "
                    f"obj={row.get('objective_value')} wall={row.get('wall_time_s')}s "
                    f"solver={row.get('solver_status') or '-'}",
                    flush=True,
                )


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Run the OpenBinding4Placement (CLASP-FaaS) campaign")
    parser.add_argument("--corpus", default=str(DEFAULT_CORPUS))
    parser.add_argument("--results", default=str(DEFAULT_RESULTS))
    parser.add_argument("--gateway", default=DEFAULT_GATEWAY)
    parser.add_argument("--applications", default=None, help="comma-separated app ids")
    parser.add_argument("--sizes", default=None, help="comma-separated infra sizes")
    parser.add_argument("--engines", default=None, help="comma-separated engine ids")
    parser.add_argument("--time-budget-ms", type=int, default=TIME_BUDGET_MS,
                        help="wall-clock stopping criterion shared by all algorithms")
    parser.add_argument("--status", action="store_true",
                        help="print campaign progress and exit")
    args = parser.parse_args()

    if args.status:
        print_status(corpus=Path(args.corpus), results_dir=Path(args.results))
        raise SystemExit(0)

    run_campaign(
        corpus=Path(args.corpus),
        results_dir=Path(args.results),
        base_url=args.gateway,
        applications={a.strip() for a in args.applications.split(",")} if args.applications else None,
        sizes={int(s) for s in args.sizes.split(",")} if args.sizes else None,
        engines={e.strip() for e in args.engines.split(",")} if args.engines else None,
        time_budget_ms=args.time_budget_ms,
    )
