apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openbinding
resources:
  - ../../base
  - ../../space
patches:
  - target:
      kind: ConfigMap
      name: gateway-config
    patch: |-
      - op: replace
        path: /data/SPACE_ENABLED
        value: "true"
      - op: add
        path: /data/SPACE_URL
        value: http://space-api:3000
      - op: add
        path: /data/SPACE_PRICING_VERSION
        value: 0.1.0
