"""jobs keep the options they were given

A job recorded the instance it was asked to solve and not the options, so a
past solve could be inspected but not repeated: a heuristic's answer is only
reproducible with the seed it was given.

Nullable, because every job that already exists was solved without this being
recorded, and inventing an empty options object for them would claim they were
solved with none.


Revision ID: 441e59a50be2
Revises: 445faae19643
Create Date: 2026-07-30 15:46:36.278747+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '441e59a50be2'
down_revision: Union[str, None] = '445faae19643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('options', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('options')

    # ### end Alembic commands ###
