"""federated engines: somebody else's solver as a row

Adding an engine has always meant a Python plugin, a manifest file, an
environment variable and a deployment. This table is those four things as data,
so that a user can register their own solver at runtime.

The manifest is stored whole rather than exploded into columns. It is a
versioned document read by a Pydantic model that already knows its shape, so a
migration per manifest field would buy nothing; the columns beside it are only
the ones the database needs in order to find rows.

``credential_encrypted`` holds Fernet ciphertext and is never read back out to
anybody - the same one-way contract the api_keys table offers for keys issued in
the other direction.

Revision ID: 445faae19643
Revises: 7ba4d278e76c
Create Date: 2026-07-30 09:14:11.402188+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '445faae19643'
down_revision: Union[str, None] = '7ba4d278e76c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('federated_engines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engine_id', sa.String(length=160), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('openapi_document', sa.JSON(), nullable=True),
    sa.Column('visibility', sa.Enum('private', 'pending_review', 'public', name='enginevisibility', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('draft', 'verifying', 'active', 'failed', 'disabled', name='enginestatus', native_enum=False, length=32), nullable=False),
    sa.Column('credential_encrypted', sa.String(length=2048), nullable=True),
    sa.Column('conformance_report', sa.JSON(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_failures', sa.Integer(), nullable=False, server_default=sa.text('0')),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_federated_engines_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_federated_engines'))
    )
    with op.batch_alter_table('federated_engines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_federated_engines_engine_id'), ['engine_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_federated_engines_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('federated_engines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_federated_engines_owner_id'))
        batch_op.drop_index(batch_op.f('ix_federated_engines_engine_id'))

    op.drop_table('federated_engines')
    # ### end Alembic commands ###
