"""collaborative platform baseline

Revision ID: 6e8de7683914
Revises: e12f4a7c9b30
Create Date: 2026-09-01 16:40:11.938935+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6e8de7683914'
down_revision: Union[str, None] = 'e12f4a7c9b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column(
            'plan_cache', existing_type=sa.String(length=16), type_=sa.String(length=128),
            server_default=None,
        )

    op.create_table('auth_identities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=160), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_identities')),
    sa.UniqueConstraint('provider', 'subject', name='uq_identity_provider_subject')
    )
    with op.batch_alter_table('auth_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_identities_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_identities_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_identities_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=240), nullable=False),
    sa.Column('body', sa.String(length=4000), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('billing_sponsor_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('parent_id IS NULL OR parent_id <> id', name=op.f('ck_organizations_organization_not_own_parent')),
    sa.ForeignKeyConstraint(['billing_sponsor_user_id'], ['users.id'], name=op.f('fk_organizations_billing_sponsor_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_organizations_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_id'], ['organizations.id'], name=op.f('fk_organizations_parent_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_billing_sponsor_user_id'), ['billing_sponsor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_prefix', sa.String(length=24), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens'))
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_prefix'), ['token_prefix'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('pricing_releases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('digest', sa.String(length=80), nullable=False),
    sa.Column('sphere_organization', sa.String(length=64), nullable=False),
    sa.Column('sphere_organization_id', sa.String(length=128), nullable=False),
    sa.Column('sphere_slug', sa.String(length=64), nullable=False),
    sa.Column('sphere_state', sa.Enum('PRIVATE_DRAFT', 'PUBLIC_RELEASE', name='pricingspherestate', native_enum=False, length=32), nullable=False),
    sa.Column('public_url', sa.String(length=1024), nullable=True),
    sa.Column('space_state', sa.Enum('NOT_DEPLOYED', 'ACTIVE', 'DRAINING', 'ARCHIVED', name='pricingspacestate', native_enum=False, length=32), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('changelog', sa.String(length=4000), nullable=False),
    sa.Column('migration_manifest', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("sphere_organization = 'OpenBinding'", name=op.f('ck_pricing_releases_pricing_fixed_organization')),
    sa.CheckConstraint("sphere_slug = 'openbinding'", name=op.f('ck_pricing_releases_pricing_fixed_slug')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_pricing_releases_created_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pricing_releases')),
    sa.UniqueConstraint('version', name='uq_pricing_release_version')
    )
    with op.batch_alter_table('pricing_releases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pricing_releases_digest'), ['digest'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricing_releases_is_live'), ['is_live'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricing_releases_version'), ['version'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=96), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_events_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_events_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_organization_id'), ['organization_id'], unique=False)

    op.create_table('organization_invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='organizationrole', native_enum=False, length=32), nullable=False),
    sa.Column('token_prefix', sa.String(length=24), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('invited_by_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_id'], ['users.id'], name=op.f('fk_organization_invitations_accepted_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], name=op.f('fk_organization_invitations_invited_by_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_invitations_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_invitations'))
    )
    with op.batch_alter_table('organization_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_invitations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_invitations_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_invitations_token_prefix'), ['token_prefix'], unique=True)

    op.create_table('organization_memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='organizationrole', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_memberships_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_organization_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_memberships')),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_organization_member')
    )
    with op.batch_alter_table('organization_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_memberships_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('visibility', sa.Enum('private', 'public', name='visibility', native_enum=False, length=32), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_projects_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_projects_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_project_org_slug')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_slug'), ['slug'], unique=False)

    op.create_table('artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('digest', sa.String(length=80), nullable=False),
    sa.Column('media_type', sa.String(length=160), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_uri', sa.String(length=1024), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_artifacts_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_artifacts_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_artifacts_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts')),
    sa.UniqueConstraint('project_id', 'digest', name='uq_artifact_project_digest')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_digest'), ['digest'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_project_id'), ['project_id'], unique=False)

    op.create_table('binding_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_binding_cases_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_binding_cases_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_binding_cases')),
    sa.UniqueConstraint('project_id', 'slug', name='uq_binding_case_project_slug')
    )
    with op.batch_alter_table('binding_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_binding_cases_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_binding_cases_slug'), ['slug'], unique=False)

    op.create_table('project_resources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('kind', sa.String(length=128), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_project_resources_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_resources_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_resources')),
    sa.UniqueConstraint('project_id', 'slug', name='uq_project_resource_slug')
    )
    with op.batch_alter_table('project_resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_resources_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_resources_slug'), ['slug'], unique=False)

    op.create_table('collections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_collections_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_collections_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections')),
    sa.UniqueConstraint('project_id', 'slug', name='uq_collection_project_slug')
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collections_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collections_slug'), ['slug'], unique=False)

    op.create_table('studies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('state', sa.Enum('draft', 'ready', name='studystate', native_enum=False, length=32), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_studies_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_studies_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_studies')),
    sa.UniqueConstraint('project_id', 'slug', name='uq_study_project_slug')
    )
    with op.batch_alter_table('studies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studies_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_studies_slug'), ['slug'], unique=False)

    op.create_table('binding_case_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('binding_case_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(length=80), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.Column('source_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('revision > 0', name=op.f('ck_binding_case_revisions_binding_case_revision_positive')),
    sa.ForeignKeyConstraint(['binding_case_id'], ['binding_cases.id'], name=op.f('fk_binding_case_revisions_binding_case_id_binding_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_binding_case_revisions_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['v1_instance_snapshots.id'], name=op.f('fk_binding_case_revisions_source_snapshot_id_v1_instance_snapshots'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_binding_case_revisions')),
    sa.UniqueConstraint('binding_case_id', 'digest', name='uq_binding_case_digest'),
    sa.UniqueConstraint('binding_case_id', 'revision', name='uq_binding_case_revision')
    )
    with op.batch_alter_table('binding_case_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_binding_case_revisions_binding_case_id'), ['binding_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_binding_case_revisions_digest'), ['digest'], unique=False)
        batch_op.create_index(batch_op.f('ix_binding_case_revisions_source_snapshot_id'), ['source_snapshot_id'], unique=False)

    op.create_table('project_resource_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_resource_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(length=80), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('revision > 0', name=op.f('ck_project_resource_revisions_project_resource_revision_positive')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_project_resource_revisions_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_resource_id'], ['project_resources.id'], name=op.f('fk_project_resource_revisions_project_resource_id_project_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_resource_revisions')),
    sa.UniqueConstraint('project_resource_id', 'digest', name='uq_project_resource_digest'),
    sa.UniqueConstraint('project_resource_id', 'revision', name='uq_project_resource_revision')
    )
    with op.batch_alter_table('project_resource_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_resource_revisions_digest'), ['digest'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_resource_revisions_project_resource_id'), ['project_resource_id'], unique=False)

    op.create_table('collection_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(length=80), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('revision > 0', name=op.f('ck_collection_revisions_collection_revision_positive')),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_collection_revisions_collection_id_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_collection_revisions_created_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_revisions')),
    sa.UniqueConstraint('collection_id', 'digest', name='uq_collection_revision_digest'),
    sa.UniqueConstraint('collection_id', 'revision', name='uq_collection_revision')
    )
    with op.batch_alter_table('collection_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_revisions_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_revisions_digest'), ['digest'], unique=False)

    op.create_table('study_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('study_id', sa.Uuid(), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('queued', 'running', 'completed', 'partial', 'failed', 'cancelled', name='runstate', native_enum=False, length=32), nullable=False),
    sa.Column('matrix_digest', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('run_number > 0', name=op.f('ck_study_runs_study_run_number_positive')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_study_runs_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_study_runs_study_id_studies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_runs')),
    sa.UniqueConstraint('study_id', 'run_number', name='uq_study_run_number')
    )
    with op.batch_alter_table('study_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_runs_matrix_digest'), ['matrix_digest'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_runs_study_id'), ['study_id'], unique=False)

    op.create_table('collection_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collection_revision_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('target_kind', sa.String(length=32), nullable=False),
    sa.Column('target_digest', sa.String(length=80), nullable=False),
    sa.Column('target_ref', sa.JSON(), nullable=False),
    sa.Column('added_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('position >= 0', name=op.f('ck_collection_items_collection_item_position_nonnegative')),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], name=op.f('fk_collection_items_added_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['collection_revision_id'], ['collection_revisions.id'], name=op.f('fk_collection_items_collection_revision_id_collection_revisions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_items')),
    sa.UniqueConstraint('collection_revision_id', 'position', name='uq_collection_item_position'),
    sa.UniqueConstraint('collection_revision_id', 'target_kind', 'target_digest', name='uq_collection_item_target')
    )
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_items_collection_revision_id'), ['collection_revision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_items_target_digest'), ['target_digest'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('study_run_id', sa.Uuid(), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.Column('digest', sa.String(length=80), nullable=False),
    sa.Column('state', sa.Enum('draft', 'frozen', name='reportstate', native_enum=False, length=32), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_reports_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_reports_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_run_id'], ['study_runs.id'], name=op.f('fk_reports_study_run_id_study_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports')),
    sa.UniqueConstraint('project_id', 'slug', name='uq_report_project_slug')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_digest'), ['digest'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_study_run_id'), ['study_run_id'], unique=False)

    op.create_table('study_cells',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('study_run_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('binding_case_revision_id', sa.Uuid(), nullable=False),
    sa.Column('engine_ref', sa.JSON(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=80), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.Enum('queued', 'running', 'completed', 'partial', 'failed', 'cancelled', name='runstate', native_enum=False, length=32), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_study_cells_study_cell_ordinal_nonnegative')),
    sa.ForeignKeyConstraint(['binding_case_revision_id'], ['binding_case_revisions.id'], name=op.f('fk_study_cells_binding_case_revision_id_binding_case_revisions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_study_cells_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['study_run_id'], ['study_runs.id'], name=op.f('fk_study_cells_study_run_id_study_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_cells')),
    sa.UniqueConstraint('study_run_id', 'fingerprint', name='uq_study_cell_fingerprint'),
    sa.UniqueConstraint('study_run_id', 'ordinal', name='uq_study_cell_ordinal')
    )
    with op.batch_alter_table('study_cells', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_cells_binding_case_revision_id'), ['binding_case_revision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_cells_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_cells_study_run_id'), ['study_run_id'], unique=False)

    op.create_table('publications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('citation', sa.JSON(), nullable=False),
    sa.Column('published_by_id', sa.Uuid(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_publications_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], name=op.f('fk_publications_published_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_publications_report_id_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publications')),
    sa.UniqueConstraint('project_id', 'slug', name='uq_publication_project_slug'),
    sa.UniqueConstraint('report_id', name='uq_publication_report')
    )
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publications_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_slug'), ['slug'], unique=False)

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('rotated_from_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_api_keys_rotated_from_id'), ['rotated_from_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_api_keys_rotated_from_id_api_keys'), 'api_keys', ['rotated_from_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancellation_requested', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('retry_of_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('organization_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('project_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('billing_sponsor_user_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_jobs_billing_sponsor_user_id'), ['billing_sponsor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_retry_of_id'), ['retry_of_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_jobs_project_id_projects'), 'projects', ['project_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_jobs_billing_sponsor_user_id_users'), 'users', ['billing_sponsor_user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_jobs_organization_id_organizations'), 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_jobs_retry_of_id_jobs'), 'jobs', ['retry_of_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_enabled', sa.Boolean(), server_default=sa.true(), nullable=False))
        batch_op.add_column(sa.Column('preferences', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferences')
        batch_op.drop_column('password_enabled')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column(
            'plan_cache', existing_type=sa.String(length=128), type_=sa.String(length=16),
            server_default=None,
        )

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_jobs_retry_of_id_jobs'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_jobs_organization_id_organizations'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_jobs_billing_sponsor_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_jobs_project_id_projects'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_jobs_retry_of_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_project_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_billing_sponsor_user_id'))
        batch_op.drop_column('billing_sponsor_user_id')
        batch_op.drop_column('project_id')
        batch_op.drop_column('organization_id')
        batch_op.drop_column('retry_of_id')
        batch_op.drop_column('cancellation_requested')

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_api_keys_rotated_from_id_api_keys'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_api_keys_rotated_from_id'))
        batch_op.drop_column('rotated_from_id')
        batch_op.drop_column('expires_at')

    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publications_slug'))
        batch_op.drop_index(batch_op.f('ix_publications_report_id'))
        batch_op.drop_index(batch_op.f('ix_publications_project_id'))

    op.drop_table('publications')
    with op.batch_alter_table('study_cells', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_cells_study_run_id'))
        batch_op.drop_index(batch_op.f('ix_study_cells_job_id'))
        batch_op.drop_index(batch_op.f('ix_study_cells_binding_case_revision_id'))

    op.drop_table('study_cells')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_study_run_id'))
        batch_op.drop_index(batch_op.f('ix_reports_slug'))
        batch_op.drop_index(batch_op.f('ix_reports_project_id'))
        batch_op.drop_index(batch_op.f('ix_reports_digest'))

    op.drop_table('reports')
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_items_target_digest'))
        batch_op.drop_index(batch_op.f('ix_collection_items_collection_revision_id'))

    op.drop_table('collection_items')
    with op.batch_alter_table('study_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_runs_study_id'))
        batch_op.drop_index(batch_op.f('ix_study_runs_matrix_digest'))

    op.drop_table('study_runs')
    with op.batch_alter_table('collection_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_revisions_digest'))
        batch_op.drop_index(batch_op.f('ix_collection_revisions_collection_id'))

    op.drop_table('collection_revisions')
    with op.batch_alter_table('binding_case_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_binding_case_revisions_source_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_binding_case_revisions_digest'))
        batch_op.drop_index(batch_op.f('ix_binding_case_revisions_binding_case_id'))

    op.drop_table('binding_case_revisions')
    with op.batch_alter_table('project_resource_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_resource_revisions_project_resource_id'))
        batch_op.drop_index(batch_op.f('ix_project_resource_revisions_digest'))

    op.drop_table('project_resource_revisions')
    with op.batch_alter_table('studies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studies_slug'))
        batch_op.drop_index(batch_op.f('ix_studies_project_id'))

    op.drop_table('studies')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_slug'))
        batch_op.drop_index(batch_op.f('ix_collections_project_id'))

    op.drop_table('collections')
    with op.batch_alter_table('binding_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_binding_cases_slug'))
        batch_op.drop_index(batch_op.f('ix_binding_cases_project_id'))

    op.drop_table('binding_cases')
    with op.batch_alter_table('project_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_resources_slug'))
        batch_op.drop_index(batch_op.f('ix_project_resources_project_id'))

    op.drop_table('project_resources')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_project_id'))
        batch_op.drop_index(batch_op.f('ix_artifacts_organization_id'))
        batch_op.drop_index(batch_op.f('ix_artifacts_expires_at'))
        batch_op.drop_index(batch_op.f('ix_artifacts_digest'))

    op.drop_table('artifacts')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_slug'))
        batch_op.drop_index(batch_op.f('ix_projects_organization_id'))

    op.drop_table('projects')
    with op.batch_alter_table('organization_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_organization_memberships_organization_id'))

    op.drop_table('organization_memberships')
    with op.batch_alter_table('organization_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_invitations_token_prefix'))
        batch_op.drop_index(batch_op.f('ix_organization_invitations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_organization_invitations_email'))

    op.drop_table('organization_invitations')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    with op.batch_alter_table('pricing_releases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pricing_releases_version'))
        batch_op.drop_index(batch_op.f('ix_pricing_releases_is_live'))
        batch_op.drop_index(batch_op.f('ix_pricing_releases_digest'))

    op.drop_table('pricing_releases')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_prefix'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))
        batch_op.drop_index(batch_op.f('ix_organizations_parent_id'))
        batch_op.drop_index(batch_op.f('ix_organizations_billing_sponsor_user_id'))

    op.drop_table('organizations')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_kind'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('auth_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_identities_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_identities_subject'))
        batch_op.drop_index(batch_op.f('ix_auth_identities_provider'))

    op.drop_table('auth_identities')
    # ### end Alembic commands ###
